package io.kinoplan.utils.date

object DatePattern {
  val `yyyy-MM-dd` = "yyyy-MM-dd"
  val `dd-MM-yyyy` = "dd-MM-yyyy"
  val `dd.MM.yyyy` = "dd.MM.yyyy"
  val `dd.MM.yy` = "dd.MM.yy"
  val `d MMMM` = "d MMMM"
  val `dd MMMM yyyy` = "dd MMMM yyyy"
  val `d MMMM yyyy` = "d MMMM yyyy"
  val `d MMMM, EEEE` = "d MMMM, EEEE"
  val `yyyy` = "yyyy"
  val `MMMM` = "MMMM"
  val `MM/dd/yyyy` = "MM/dd/yyyy"
  val `HH:mm:ss` = "HH:mm:ss"
  val `HH:mm` = "HH:mm"
  val `mm:ss` = "mm:ss"
  val `yyyyMMddHHmmss` = "yyyyMMddHHmmss"
  val `dd MMMM yyyy HH:mm` = "dd MMMM yyyy HH:mm"
  val `dd.MM.yyyy HH:mm` = "dd.MM.yyyy HH:mm"
  val `dd.MM.yyyy / HH:mm` = "dd.MM.yyyy / HH:mm"
  val `dd.MM.yy HH:mm` = "dd.MM.yy HH:mm"
  val `dd.MM.yyyy HH:mm:ss` = "dd.MM.yyyy HH:mm:ss"
  val `dd-MM-yyyy HH:mm:ss` = "dd-MM-yyyy HH:mm:ss"
  val `yyyy-MM-dd HH:mm:ss` = "yyyy-MM-dd HH:mm:ss"
  val `yyyy-MM-dd HH:mm:ss.SSS` = "yyyy-MM-dd HH:mm:ss.SSS"
  val `yyyy-MM-dd HH:mm` = "yyyy-MM-dd HH:mm"
  val `yyyy-MM-dd'T'HH:mm:ss` = "yyyy-MM-dd'T'HH:mm:ss"
  val `yyyy-MM-dd'T'HH:mm:ss.SSS` = "yyyy-MM-dd'T'HH:mm:ss.SSS"
}
